# Generated by Django 4.2.4 on 2024-06-19 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('username', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('PASSWORD', models.CharField(max_length=225)),
                ('NAME', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='PARENTS',
            fields=[
                ('ICNUM', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('NAME', models.TextField(max_length=225)),
                ('USERNAME', models.TextField(max_length=255)),
                ('PASSWORD', models.CharField(max_length=225)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('ADDRESS', models.CharField(max_length=225)),
                ('NOMPHONE', models.CharField(max_length=255)),
                ('RELATIONSHIP', models.TextField(max_length=255)),
                ('RELIGION', models.TextField(max_length=225)),
                ('INCOME', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='STAFF',
            fields=[
                ('STICNUM', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('NAME', models.TextField(max_length=225)),
                ('PASSWORD', models.CharField(max_length=225)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('PHONENUMBER', models.CharField(max_length=225)),
                ('ADDRESS', models.CharField(max_length=225)),
                ('POSSITION', models.TextField(max_length=225)),
                ('EDUCATION', models.CharField(max_length=225)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TASKAapp.admin')),
            ],
        ),
        migrations.CreateModel(
            name='CHILD',
            fields=[
                ('mykadnum', models.CharField(max_length=125, primary_key=True, serialize=False)),
                ('cname', models.TextField(max_length=125)),
                ('age', models.CharField(max_length=125)),
                ('salinanmykid', models.ImageField(upload_to='images/')),
                ('salinanICparent', models.ImageField(upload_to='images/')),
                ('salinansuratberanak', models.ImageField(upload_to='images/')),
                ('salinanimunisasianak', models.ImageField(upload_to='images/')),
                ('interfacebukukesihatan', models.ImageField(upload_to='images/')),
                ('ICNUM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TASKAapp.parents')),
                ('STICNUM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TASKAapp.staff')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TASKAapp.admin')),
            ],
        ),
    ]
